### PR TITLE
Linked eigen3 to target board

### PR DESCRIPTION
**Pull request by JMoore5353**
The implementation of the new mixing system depends on Eigen. It doesn't use any dynamically allocated memory, so it should be fine to run on the microcontroller. I suspect Eigen will be useful in the future as we develop a mixing system for ROSvtol.

### CODE REVIEW

**Review by bsutherland333 — COMMENTED** [review]
We don't need to add eigen as a dependency to the varmint board, as eigen is only used in the core rosflight library. The build workflows in this use a dummy class in place of the actual rosflight_firmware, so no eigen is involved.

**Comment by avtoku** [comment]
Do we want to delete this dead branch?

**Comment by JMoore5353** [comment]
> We don't need to add eigen as a dependency to the varmint board, as eigen is only used in the core rosflight library. The build workflows in this use a dummy class in place of the actual rosflight_firmware, so no eigen is involved.

I did this because pushing the new mixer updates in the `rosflight_firmware` that require Eigen were not building unless I linked Eigen to the targets. @bsutherland333 maybe you can show me the correct way to add that dependency to the firmware?

**Comment by bsutherland333** [comment]
@JMoore5353 you would do the same thing you did here, but in the rosflight_firmware repository. varmint_h7 would be unchanged.

**Comment by avtoku** [comment]
Can you add them to the rosflight_firmware/CMakeLists.txt ?

**Comment by JMoore5353** [comment]
Sounds good. I got it figured out in the `rosflight_firmware/CMakeLists.txt`. Thanks for the help.

**Pull request closed without merging**
